In [2]:
import pandas as pd
import numpy as np
import names
import random
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi
from datetime import date
from datetime import timedelta

random.seed(0)
jsonFile = 'C:/Users/wasadmin/Desktop/GIT/Capstone/data/pets10k.json'
df = pd.read_json(jsonFile)

In [3]:
#Server connection
uri = "mongodb+srv://admin:capstoneproject@cluster0.vzztiaj.mongodb.net/?retryWrites=true&w=majority"
# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))
# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [4]:
#Get ref to products and categories collections
mydb = client["capstonedb"]
products = mydb["products"]
categories = mydb["categories"]
cursor = categories.find({})
categoryObjectIds = []
for doc in cursor:
    categoryObjectIds.append(doc['_id'])

In [5]:
#Convert ObjectId objects within the array into string
categoryStrs = []
for i in categoryObjectIds:
    categoryStrs.append(str(i))
categoryStrs

['65c4fbf8ad328e73f11fb8fb',
 '65c4fd9aad328e73f11fb8fc',
 '65c4fe04ad328e73f11fb8fe',
 '65c4fe35ad328e73f11fb8ff']

In [6]:
personality_descriptors = [
    "Affectionate",
    "Adventurous",
    "Alert",
    "Amiable",
    "Articulate",
    "Assertive",
    "Balanced",
    "Bold",
    "Calm",
    "Caring",
    "Cautious",
    "Charismatic",
    "Charming",
    "Collaborative",
    "Compassionate",
    "Confident",
    "Conscientious",
    "Creative",
    "Curious",
    "Dependable",
    "Determined",
    "Diplomatic",
    "Easygoing",
    "Efficient",
    "Empathetic",
    "Energetic",
    "Enthusiastic",
    "Flexible",
    "Frank",
    "Friendly",
    "Funny",
    "Gentle",
    "Honest",
    "Humorous",
    "Independent",
    "Individualistic",
    "Intellectual",
    "Intuitive",
    "Introspective",
    "Kind",
    "Leader",
    "Level-headed",
    "Loyal",
    "Loving",
    "Mature",
    "Methodical",
    "Motivated",
    "Neat",
    "Observant",
    "Optimistic",
    "Organized",
    "Original",
    "Outgoing",
    "Patient",
    "Peace-loving",
    "Persuasive",
    "Playful",
    "Practical",
    "Precise",
    "Problem-solver",
    "Quick-witted",
    "Reliable",
    "Responsible",
    "Respectful",
    "Resourceful",
    "Romantic",
    "Self-disciplined",
    "Selfless",
    "Sensitive",
    "Sociable",
    "Sincere",
    "Spontaneous",
    "Strong",
    "Thoughtful",
    "Trustworthy",
    "Unique",
    "Visionary",
    "Warm",
    "Witty",
    "Zestful",
]
descriptions = [
    "Energetic cuddle buddy",
    "Loyal furball friend",
    "Playful mischief maker",
    "Purring stress reliever",
    "Feathery cuddle monster",
    "Soft, curious companion",
    "Adventurous outdoor pal",
    "Happy tail wagger",
    "Affectionate lap warmer",
    "Trustworthy sidekick",
    "Independent house guest",
    "Curious feathered friend",
    "Active scaly companion",
    "Quiet aquarium resident",
    "Independent cuddle monster",
    "Soft, silent companion",
    "Nocturnal cuddle buddy",
    "Playful water enthusiast",
    "Busy shelled housemate",
    "Aloof feathered observer",
    "Clumsy fur tornado",
    "Messy feathered comedian",
    "Vocal, opinionated friend",
    "Shedding cuddle monster",
    "Purring dust bunny magnet",
    "Soft, slobbery companion",
    "Cheeky, feathered acrobat",
    "Energetic barking alarm",
    "Playful, destructive gremlin",
    "Independent, mischievous floof",
    "Sunbeam-loving fluffball",
    "Inquisitive, feathered explorer",
    "Waddling ball of sunshine",
    "Purring symphony composer",
    "Fin-tastic underwater dancer",
    "Trusty, shadow-like companion",
    "Energetic, tail-wagging whirlwind",
    "Soft, purring heat source",
    "Playful, feathery chatterbox",
    "Loyal, watchful protector",
    "Independent, nocturnal shadow",
    "Curious, whiskered investigator",
    "Graceful, silent swimmer",
    "Quiet, shelled observer",
    "Independent, feathery acrobat",
    "Soft, quiet cuddlebug",
    "Nocturnal, chirping serenade",
    "Playful, aquatic explorer",
    "Busy, burrowing resident",
    "Aloof, feathered watcher",
    "Tiny, destructive hurricane",
    "Feathered dust bunny creator",
    "Chatty, opinionated alarm clock",
    "Shedding purring machine",
    "Scales in unexpected places",
    "Sleepy, snoring cuddle monster",
    "Nocturnal, squeaking mischief",
    "Energetic, bark-happy comedian",
    "Playful, feathery kleptomaniac",
    "Independent, mischievous fluffball"
]
sizes =[
   "Ginormous",
   "Large",
   "Medium",
   "Small",
   "Tiny",
   "Micro"
]
sold = ['true','false','false','false','false','false','false']
#Field randomizers
def getNRandomWords(words,n):
  word = []
  size = len(words)
  for i in range(0,n):
     word.append(words[random.randint(0,size - 1)])
  if n == 1:
     return word[0]
  return word

def getRandomInt(min,max):
    return random.randint(min,max)

def getRandomDec(min,max):
   return random.uniform(min,max)

def get_random_date(start_date, end_date):
  time_between_dates = end_date - start_date
  days_between_dates = time_between_dates.days
  random_number_of_days = random.randrange(days_between_dates + 1)
  random_date = start_date + timedelta(days=random_number_of_days)
  return random_date

In [11]:

import requests
dogsrc = "https://api.animality.xyz/img/dog"
catsrc = "https://api.animality.xyz/img/cat"
birdsrc = "https://api.animality.xyz/img/bird"
aquaticsrc = "https://api.animality.xyz/img/fish"

#Make a conversion dict or something from the categories object ids
#Get all records of category 'C'
#For each cageory in catgeory 'C', generate len('C') images, 80% unique .unique()
#Considerations: the dataframe will have to be : new df2['C'] = df1['C'].addcolumn() 

async def getImages():
    response = requests.get(dogsrc)
    return response.json()
task = await getImages()

async def getCatImages():
    response = requests.get(catsrc)
    return response.json()
cat_task = await getCatImages()

async def getBirdImages():
    response = requests.get(birdsrc)
    return response.json()
bird_task = await getBirdImages()

async def getAquaticImages():
    response = requests.get(aquaticsrc)
    return response.json()
aquatic_task = await getAquaticImages()

from IPython.display import Image
from IPython.core.display import HTML 
Image(url= task['image'])
Image(url= cat_task['image'])
Image(url= bird_task['image'])
Image(url= aquatic_task['image'])

In [19]:
category_images = {"65c4fbf8ad328e73f11fb8fb" : task, "65c4fd9aad328e73f11fb8fc" : cat_task, 
                   "65c4fe04ad328e73f11fb8fe" : bird_task, "65c4fe35ad328e73f11fb8ff" : aquatic_task }

rob_df = pd.DataFrame(category_images)
rob_df

,65c4fbf8ad328e73f11fb8fb,65c4fd9aad328e73f11fb8fc,65c4fe04ad328e73f11fb8fe,65c4fe35ad328e73f11fb8ff
animal,dog,cat,bird,fish
image,https://cdn.animality.xyz/dog/24.png,https://cdn.animality.xyz/cat/6.png,https://cdn.animality.xyz/bird/16.png,https://cdn.animality.xyz/fish/13.png
image_id,f0d8ad4b-73c9-47ba-a4e4-55b9ad9c6f5c,e7017d26-313d-4d91-826c-21ef137acdf0,73129bf2-2f40-4acf-8d34-9e7f05141d02,fcd0a0e1-5bab-409e-861a-234d87afd8be

In [22]:
rob_df2 = rob_df
rob_df2['image'] = category_images
rob_df2

,65c4fbf8ad328e73f11fb8fb,65c4fd9aad328e73f11fb8fc,65c4fe04ad328e73f11fb8fe,65c4fe35ad328e73f11fb8ff,image
animal,dog,cat,bird,fish,NaN
image,https://cdn.animality.xyz/dog/24.png,https://cdn.animality.xyz/cat/6.png,https://cdn.animality.xyz/bird/16.png,https://cdn.animality.xyz/fish/13.png,NaN
image_id,f0d8ad4b-73c9-47ba-a4e4-55b9ad9c6f5c,e7017d26-313d-4d91-826c-21ef137acdf0,73129bf2-2f40-4acf-8d34-9e7f05141d02,fcd0a0e1-5bab-409e-861a-234d87afd8be,NaN

In [13]:
def getCategoryImages():
    if categoryStrs == (category_images[0]):
        return task
    elif categoryStrs == (category_images[1]):
        return cat_task
    elif categoryStrs == (category_images[2]):
        return bird_task
    elif categoryStrs == (category_images[3]):
        return aquatic_task

In [15]:
#Generate fields

generated_records = []
for i in range(0,1000):
    current_record = {
        "name": names.get_first_name(),
		"released": get_random_date(date.today() - timedelta(days=500),date.today()),
		"age": str(getRandomInt(0,15)),
		"desc": getNRandomWords(descriptions,1),
		"size": getNRandomWords(sizes,1),
		"personality": getNRandomWords(personality_descriptors,1),
		"price": str(getRandomInt(100,30000)),
		"sold": getNRandomWords(sold,1),
		"popularity": str(getRandomInt(0,2000)),
		"category_id": categoryStrs[getRandomInt(0,3)],
        
    }
    #"images": ["url"]
    generated_records.append(current_record)

In [26]:

df1 = pd.DataFrame(generated_records)

In [27]:
df1

,name,released,age,desc,size,personality,price,sold,popularity,category_id
0,Sandra,2023-07-14,1,Happy tail wagger,Ginormous,Persuasive,12335,false,250,65c4fe04ad328e73f11fb8fe
1,Edna,2024-01-20,3,Purring stress reliever,Large,Confident,28586,false,937,65c4fbf8ad328e73f11fb8fb
2,Irene,2022-12-05,0,"Nocturnal, chirping serenade",Large,Original,3689,true,1037,65c4fd9aad328e73f11fb8fc
3,Billy,2022-11-24,2,"Playful, feathery kleptomaniac",Ginormous,Witty,10817,false,747,65c4fbf8ad328e73f11fb8fb
4,Nancy,2023-01-19,1,"Quiet, shelled observer",Tiny,Sociable,16157,true,1186,65c4fd9aad328e73f11fb8fc
...,...,...,...,...,...,...,...,...,...,...
995,Ronald,2023-03-29,7,Nocturnal cuddle buddy,Tiny,Energetic,24691,false,115,65c4fd9aad328e73f11fb8fc
996,Erik,2024-01-04,9,"Trusty, shadow-like companion",Medium,Efficient,19124,false,205,65c4fe35ad328e73f11fb8ff
997,Christina,2023-03-27,1,"Quiet, shelled observer",Tiny,Warm,4565,false,1239,65c4fe04ad328e73f11fb8fe
998,China,2023-06-16,9,Independent cuddle monster,Micro,Sociable,5256,false,275,65c4fd9aad328e73f11fb8fc
999,Rosalba,2023-04-17,3,"Soft, quiet cuddlebug",Tiny,Determined,2258,false,968,65c4fbf8ad328e73f11fb8fb

In [31]:
def CategoryImages(category_id):
    if category_id == '65c4fbf8ad328e73f11fb8fb':
        return task
    elif category_id == '65c4fd9aad328e73f11fb8fc':
        return cat_task
    elif category_id == '65c4fe04ad328e73f11fb8fe':
        return bird_task
    elif category_id == '65c4fe35ad328e73f11fb8ff':
        return aquatic_task

In [32]:
df['image'] = df['category_id'].apply(CategoryImages)

In [33]:
df

,name,released,age,desc,size,personality,price,sold,popularity,category_id,image
0,Cedric,"Jan 24, 2023",2.5,Angel Devil Miscreant Well-adjusted,large,Neutral,13807,False,147,0,None
1,Zoe,"Oct 7, 2023",8.5,Smart Trainable Curious Gentle,tiny,Powerful,16907,False,856,1,None
2,Emily,"Dec 1, 2023",7.5,Curious Gentle Patient Happy,large,Neutral,14051,False,806,2,None
3,Justina,"Aug 21, 2023",7.5,Energetic Cuddly Friendly Smart,tiny,Menacing,2030,False,550,3,None
4,Astra,"Feb 7, 2023",3.5,Hungry Creature Evil Good,tiny,Guard,8929,False,94,3,None
...,...,...,...,...,...,...,...,...,...,...,...
995,Vanna,"May 1, 2023",3.5,Trainable Curious Gentle Patient,large,Hungry,17858,False,170,1,None
996,Rebecca,"Aug 11, 2023",6.5,Patient Happy Fun-loving Trustworthy,small,Hero,6049,False,248,2,None
997,Burke,"Jan 11, 2024",1.5,Curious Gentle Patient Happy,large,Good,12642,False,215,1,None
998,Francesca,"Sep 30, 2023",5.5,Loving Obedient Energetic Cuddly,tiny,Lack-luster,17116,True,858,1,None
999,Leandra,"Apr 21, 2023",9.5,Angel Devil Miscreant Well-adjusted,medium,Neutral,9906,False,868,0,None